version: '3.8'

services:
  oracle-db:
    #
    image: gvenzl/oracle-free:23-slim
    container_name: oracle23c
    environment:
      # Usuario: system
      - ORACLE_PASSWORD=cenha
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s system/cenha@localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 10

volumes:
  oracle_data:
