services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_PROFILE=prod
    depends_on:
      - oracle
      - db2

  oracle:
    image: doctorkirk/oracle-19c
    environment:
      ORACLE_PASSWORD: mypassword
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

  db2:
    image: icr.io/db2_community/db2
    environment:
      DB2INST1_PASSWORD: mypassword
      LICENSE: accept
    ports:
      - "50000:50000"
    volumes:
      - db2_data:/database

volumes:
  oracle_data:
  db2_data: